### ISSUE TITLE
你好，请问下咱们这个分词如何加载用户词典哈

### ISSUE THREAD

**Issue by hei-my** [howl-anderson/rasa_chinese_service#2]
你好，请问下咱们这个分词如何加载用户词典哈，`rasa_chinese.nlu.tokenizers.lm_tokenizer.LanguageModelTokenizer`
需要修改源码```
AutoTokenizer.from_pretrained(
        model_weights, cache_dir=cache_dir, use_fast=True
    )
```，加入pretrained_model_name_or_path吗？

**Comment by howl-anderson** [comment]
这个分词器不是传统意义上的中文分词器，它本质上按字分词，因此不存在加载用户字典这种需求和问题。
